version: "3"
services:
  bot:
    build: .
    container_name: astrobot
    restart: always
    tty: true
    stdin_open: true
    environment:
      - DISCORD_TOKEN={ENV_DISCORD_TOKEN}
      - CLIENT_ID={ENV_CLIENT_ID}
      - GUILD_ID={ENV_GUILD_ID}
      - DP_FORCE_YTDL_MOD={ENV_DP_FORCE}
